{% set name = "pywr" %}
{% set version = "1.1.0" %}
{% set git_rev = "v1.1.0" %}
{% set build_number = 0 %}

{% if os.environ.get("FEATURE_OLDGLIBC", "0") == "1" %}
    {% set OLDGLIBC = 1 %}
{% else %}
    {% set OLDGLIBC = 0 %}
{% endif %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: https://github.com/pywr/pywr.git
    git_rev: {{ git_rev }}

build:
    number: {{ build_number }}

    script_env:
        - FEATURE_OLDGLIBC [linux]

  features:
    - vc14  # [win]
  {% if OLDGLIBC %}
    - oldglibc
  {% endif %}


requirements:
  build:
    - python
    - vc 14  # [win]
    - setuptools
    - numpy
    - cython
    - glpk
    - lp_solve
    - future
    - packaging
    - wheel
    - setuptools_scm
    {% if OLDGLIBC %}
    - oldglibc
    {% endif %}
  run:
    - python
    - vc 14  # [win]
    - {{ pin_compatible('numpy') }}
    - pandas
    - networkx
    - glpk
    - lp_solve
    - pytables
    # Fix pytables on windows. See https://github.com/conda-forge/pytables-feedstock/issues/31#issuecomment-410695814
    - snappy  # [win]
    - xlrd
    - scipy
    - future
    - packaging
    - jupyter
    - matplotlib
    {% if OLDGLIBC %}
    - oldglibc
    {% endif %}

test:
  requires:
    - pytest
    - nbconvert
    - pygmo
    - platypus-opt
    {% if BUILD_DOC %}
    - sphinx
    - sphinx_rtd_theme
    - numpydoc
    {% endif %}

  source_files:
    - tests/*
    {% if BUILD_DOC %}
    - docs/*
    {% endif %}

about:
    home: https://github.com/pywr/pywr
    license: GPL
    license_file: LICENSE.txt
    summary: Pywr is a generalised network resource allocation model written in Python
