{% set name = "pywr" %}
{% set version = "1.0.0" %}
{% set git_rev = "v1.0.0" %}
{% set build_number = 0 %}

{% if os.environ.get("FEATURE_OLDGLIBC", "0") == "1" %}
    {% set OLDGLIBC = 1 %}
{% else %}
    {% set OLDGLIBC = 0 %}
{% endif %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: https://github.com/pywr/pywr.git
    git_rev: {{ git_rev }}

build:
    number: {{ build_number }}

    script_env:
        - FEATURE_OLDGLIBC [linux]

    {% if OLDGLIBC %}
    features:
        - oldglibc
    {% endif %}

requirements:
  build:
    - python
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
    - setuptools
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - cython
    - glpk
    - lp_solve
    - future
    - packaging
    {% if OLDGLIBC %}
    - oldglibc
    {% endif %}
  run:
    - python
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - pandas
    - networkx
    - glpk
    - lp_solve
    - pytables
    - xlrd
    - scipy
    - future
    - packaging
    - jupyter
    - matplotlib
    {% if OLDGLIBC %}
    - oldglibc
{% endif %}

test:
    requires:
        - pytest
    source_files:
        - tests/*

about:
    home: https://github.com/pywr/pywr
    license: GPL
    license_file: LICENSE.txt
    summary: Pywr is a generalised network resource allocation model written in Python
