language: generic

sudo: false

branches:
    only:
        - master

env:
    global:
      - secure: "FQZjYwRhHgVf96a+GgZRgEZPuCirsRAjWUE9VLh7JVfLwGXV/ABLUa32/KLv4/R6sT1cXg9Eo4pUxCzjjfXwJQVvaB1ttn9iWg7JX56NhT7ZVs3h5PQPG03CSwU4Tsjt3LNAadZ5inik3X8MFi4O6xg3pqaHn/NmY1+zmDBiUws1ys0hB0QWLrOzEuGyXTxMcC6Hhw2To1d1fcVA6JSY2fw3cA4axxC9XXtLOt/hn9d5wXi+6mVNcMtfKkLrNUz5aXXJM2lli/SsBQTHaZVCT7zHIYaqwaBeklkrbESBrGHNEj+yKJo1+Uu+aNxs4vkCGTGvK1nrXNgG5onqKV/5JdEyM3UVz52lrYpkY/3DuAM+oia3sICkpOSMd8UmGZy6gAC0tWr0kiJMDiESA941bJ90UtXVOsR+Zv21UDGcmjvu8HL5TWYFyCMgsMDEyxd+iVeKSlZC8rHn9siByHG/JC1eerhikmoH9yNFBRdmX8ZKZ9SJ60nwG5coFZzwiaqoezLckYbX3rxNLa7rS6gqqCJrEZzmpHzN+hGeDj3yl21z9yiBy00Oydv5eF6EkLXLDYcYWai2nFHFIiTcIu5cAIk8HRWDFXvlW4op9ETgyCjtFZ3lV+9ExCURV+OfWUDPksPrzrA1YkJuXVfxdw+spWl2CAidOCQYYbkzQ7bOG4Q="

# Travis has limited OSX resources
# Only do OSX on Python 3.6
matrix:
    include:
      - os: linux
        env: CONDA_PY=36
      - os: osx
        env: CONDA_PY=36
             MACOSX_DEPLOYMENT_TARGET=10.9        

install:
    - |
      if [ ! -f ${HOME}/miniconda3/bin/conda ] ; then
          echo "Fresh miniconda install..."
          MINICONDA_URL="https://repo.continuum.io/miniconda"
          if [ `uname` == "Darwin" ]; then
              MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
          else
              MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
          fi
          wget ${MINICONDA_URL}/${MINICONDA_FILE}
          rm -rf ${HOME}/miniconda3
          bash ${MINICONDA_FILE} -b -p ${HOME}/miniconda3
      fi
      export PATH=${HOME}/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --add channels snorfalorpagus
      
      conda update --yes conda
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-build anaconda-client

script:
    - |
      set -e
      
      # build
      conda build ./recipe

# Upload to anaconda only if master branch and not a PR.      
deploy:
    provider: script
    script: bash deploy.sh
    on:
        branch: master
